fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    powershell: 'https://github.com/puppetlabs/puppetlabs-powershell.git'
  symlinks:
    sslcertificate: '#{source_dir}'
